WIDGET_DOCS = {
    "AdSense": {
        "summary": "Google AdSense display unit for the web. It renders a reserved ad slot, loads the adsbygoogle SDK once per publisher, and lets Google fill the slot.",
        "when": "Reach for AdSense when you ship a web, PWA, or webview build and want to monetize a page with a display slot.",
        "related": ["AdMob", "Container", "Stack"],
        "tips": [
            "Both `client` and `slot` are required; until then the widget shows a dashed placeholder and requests no ad.",
            "Self-sizing formats such as `fluid` and `autorelaxed` grow with the ad, while fixed formats keep the reserved `height`.",
            "Set `test: true` only while developing; it must be off in production.",
        ],
        "accessibility": [
            "Give the surrounding section a heading so the slot is not the only content a screen reader encounters.",
        ],
        "behavior": [
            "`onLoad` fires after the SDK is ready and the unit is pushed; `onError` fires if the SDK fails to load.",
            "The SDK is injected once per `client` and shared by every AdSense unit on the page; unmounting stops further loads.",
        ],
        "basic": '''const ad = AdSense({
  client: "ca-pub-1234567890123456",
  slot: "1234567890",
});''',
        "normal": '''const ad = AdSense({
  client: "ca-pub-1234567890123456",
  slot: "1234567890",
  format: "auto",
  responsive: true,
  height: 280,
});''',
        "full": '''const ad = AdSense({
  client: "ca-pub-1234567890123456",
  slot: "1234567890",
  format: "fluid",
  responsive: true,
  width: "100%",
  height: 320,
  bgColor: "#f8fafc",
  borderColor: "#e2e8f0",
  label: "Sponsored",
  onLoad: (widget) => console.log("ad ready", widget),
  onError: (error) => console.warn("AdSense unavailable", error),
});''',
    },
    "AdMob": {
        "summary": "Google AdMob banner and full-screen ads for native Capacitor builds. It renders a placeholder that reserves banner space and drives the native plugin on mount.",
        "when": "Use AdMob in Capacitor Android or iOS apps that need banner, interstitial, or rewarded ads over the native layer.",
        "related": ["AdSense", "Container", "Stack"],
        "tips": [
            "On the web with no Capacitor plugin it degrades to the placeholder and logs one warning, so development keeps working.",
            "Keep `isTesting: true` until your real ad units are approved, then switch to production ids.",
            "Choose `position: \"top\"` or `\"bottom\"` and use `margin` to offset the banner from the device edge.",
        ],
        "accessibility": [
            "Reserve the banner height with `height` so page content does not jump under a screen reader's cursor while the ad loads.",
        ],
        "behavior": [
            "The returned element exposes `show()`, `hide()`, `showInterstitial()`, and `showRewarded()` for full-screen ads.",
            "`onLoaded` fires after the banner is shown, `onFailed` on native errors, and `onDismissed` after a full-screen ad closes; unmount removes the banner.",
        ],
        "basic": '''const banner = AdMob({
  adId: "ca-app-pub-XXXXXXXXXXXXXXXX/YYYYYYYYYY",
  isTesting: true,
});''',
        "normal": '''const banner = AdMob({
  adId: "ca-app-pub-XXXXXXXXXXXXXXXX/YYYYYYYYYY",
  position: "bottom",
  size: "ADAPTIVE_BANNER",
  margin: 8,
  isTesting: false,
});''',
        "full": '''const banner = AdMob({
  adId: "ca-app-pub-XXXXXXXXXXXXXXXX/YYYYYYYYYY",
  position: "bottom",
  size: "ADAPTIVE_BANNER",
  interstitialId: "ca-app-pub-XXXXXXXXXXXXXXXX/1111111111",
  rewardedId: "ca-app-pub-XXXXXXXXXXXXXXXX/2222222222",
  isTesting: true,
  autoShow: true,
  label: "AdMob banner",
  bgColor: "#f8fafc",
  onLoaded: (widget) => console.log("banner visible", widget),
  onFailed: (error) => console.warn("AdMob error", error),
  onDismissed: () => console.log("ad dismissed"),
});''',
    },
    "Container": {
        "summary": "General-purpose surface box. It is a flex column by default and groups children while controlling spacing, background, sizing, and overflow.",
        "when": "Reach for Container whenever you need a rectangular surface to group content or apply padding, background, and size.",
        "related": ["Row", "Column", "Stack", "Card"],
        "tips": [
            "Container is a column by default; set `direction: \"row\"` to lay children out horizontally.",
            "`bgColor` defaults to the theme surface and `overflow` defaults to `\"auto\"`, so long content scrolls.",
            "Use `expand` or `flex` to let a container share free space inside a parent flex layout.",
        ],
        "accessibility": [
            "Keep one logical section per Container so screen-reader navigation lands on meaningful groups.",
        ],
        "behavior": [
            "One child uses `child`; several use `children`; `gap` controls the space between them.",
            "`minWidth`, `maxWidth`, `minHeight`, and `maxHeight` constrain the surface, while `overflow` decides how excess content behaves.",
        ],
        "basic": '''const panel = Container({
  padding: 16,
  bgColor: "#f8fafc",
  child: Text({ text: "Hello FletBox" }),
});''',
        "normal": '''const panel = Container({
  direction: "column",
  gap: 12,
  padding: 16,
  borderRadius: 12,
  child: Text({ text: "Account settings" }),
});''',
        "full": '''const panel = Container({
  direction: "column",
  gap: 16,
  padding: 24,
  margin: 16,
  borderRadius: 16,
  bgColor: "#ffffff",
  elevation: 2,
  maxWidth: 480,
  overflow: "auto",
  children: [
    Text({ text: "Account settings", type: "h3", weight: "bold" }),
    Text({ text: "Update your profile details." }),
  ],
});''',
    },
    "Row": {
        "summary": "Horizontal flex layout that places its children side by side. It is full width and leaves height at auto by default.",
        "when": "Use Row for toolbars, button groups, and any set of items that should sit in a horizontal line.",
        "related": ["Column", "Container", "Stack", "Button"],
        "tips": [
            "`justifyContent` distributes free horizontal space and `alignItems` aligns children vertically.",
            "Add `wrap: true` when children should flow onto additional lines instead of shrinking.",
            "`gap` sets an even space between every child.",
        ],
        "accessibility": [
            "Keep the DOM order the same as the visual order so keyboard and screen-reader focus follow the layout.",
        ],
        "behavior": [
            "The element is `display: flex` with `flex-direction: row`; passing `onPress` makes the whole row interactive.",
            "Children stay in the order given and can themselves be `expand` containers that share the row's width.",
        ],
        "basic": '''const row = Row({
  gap: 8,
  children: [
    Text({ text: "Left" }),
    Text({ text: "Right" }),
  ],
});''',
        "normal": '''const row = Row({
  gap: 12,
  justifyContent: "space-between",
  alignItems: "center",
  children: [
    Text({ text: "Update your profile" }),
    Button({ text: "Save", onPress: () => console.log("saved") }),
  ],
});''',
        "full": '''const row = Row({
  gap: 16,
  justifyContent: "center",
  alignItems: "center",
  wrap: true,
  padding: 16,
  bgColor: "#f8fafc",
  borderRadius: 12,
  children: [
    Icon({ name: "person" }),
    Text({ text: "Jane Doe" }),
    Button({ text: "Profile", variant: "outlined" }),
  ],
});''',
    },
    "Column": {
        "summary": "Vertical flex layout that stacks its children one below another. It is full width and leaves height at auto by default.",
        "when": "Use Column for forms, lists of blocks, and any content that reads from top to bottom.",
        "related": ["Row", "Container", "Stack", "ListView"],
        "tips": [
            "`gap` controls the space between stacked children.",
            "Set `alignItems: \"center\"` to center children horizontally in the column.",
            "Give children `expand` to split the available height between them.",
        ],
        "accessibility": [
            "Maintain reading order from top to bottom and avoid purely visual reordering of the children.",
        ],
        "behavior": [
            "The element is `display: flex` with `flex-direction: column`; passing `onPress` makes the whole column interactive.",
            "Children stack in the order given, and `justifyContent` controls how leftover vertical space is used.",
        ],
        "basic": '''const column = Column({
  gap: 8,
  children: [
    Text({ text: "First" }),
    Text({ text: "Second" }),
  ],
});''',
        "normal": '''const column = Column({
  gap: 12,
  padding: 16,
  alignItems: "flex-start",
  children: [
    Text({ text: "Account settings", type: "h3", weight: "bold" }),
    Text({ text: "Update your profile details." }),
  ],
});''',
        "full": '''const column = Column({
  gap: 16,
  justifyContent: "flex-start",
  alignItems: "stretch",
  padding: 24,
  bgColor: "#ffffff",
  borderRadius: 16,
  children: [
    Text({ text: "Sign in", type: "h2", weight: "bold" }),
    Button({ text: "Continue", fullWidth: true, onPress: () => console.log("go") }),
    Button({ text: "Cancel", variant: "text" }),
  ],
});''',
    },
    "Stack": {
        "summary": "Overlay container that lets children occupy the same box. It is relative by default so children can be positioned, and it supports a nine-point alignment.",
        "when": "Use Stack to layer badges, overlays, captions, or any elements that should sit on top of one another.",
        "related": ["Container", "Row", "Column", "Badge"],
        "tips": [
            "Stack is `position: \"relative\"` by default, which makes it a positioning context for absolute children.",
            "`alignment` anchors children at one of nine points from top-left to bottom-right.",
            "Later children paint on top, so order them from back to front.",
        ],
        "accessibility": [
            "Make sure overlaid controls keep a logical tab order and that focus is never hidden behind another layer.",
        ],
        "behavior": [
            "The root is a plain block by default and children are laid out per `position` and `alignment`.",
            "Set `width` and `height` (or `expand`) when the stack needs a definite size for layered content.",
        ],
        "basic": '''const stack = Stack({
  children: [
    Text({ text: "Base" }),
    Text({ text: "Overlay" }),
  ],
});''',
        "normal": '''const stack = Stack({
  width: 240,
  height: 160,
  alignment: "center",
  children: [
    Container({ bgColor: "#e0e7ff", child: Text({ text: "Background" }) }),
    Text({ text: "Centered", weight: "bold" }),
  ],
});''',
        "full": '''const stack = Stack({
  width: "100%",
  height: 220,
  position: "relative",
  alignment: "bottom-right",
  children: [
    Container({ bgColor: "#f1f5f9", child: Text({ text: "Cover" }) }),
    Container({
      bgColor: "#2563eb",
      borderRadius: 8,
      padding: 8,
      child: Text({ text: "New", color: "#ffffff" }),
    }),
  ],
});''',
    },
    "ListView": {
        "summary": "Virtualized scrollable list that keeps only the visible rows plus a buffer in the DOM, so large datasets stay responsive.",
        "when": "Use ListView for long or infinite feeds, search results, and chat logs where rendering every row would be wasteful.",
        "related": ["GridView", "Column", "Container", "ListTile"],
        "tips": [
            "`renderItem` must return a widget and is called with `(item, index)`.",
            "Set `itemSize` to the real row height so the virtual scroll math stays accurate.",
            "Provide `onEndReached` to load more data and `onRefresh` to enable pull-to-refresh.",
        ],
        "accessibility": [
            "Give the list an accessible heading, since offscreen rows are intentionally absent from the DOM.",
        ],
        "behavior": [
            "The element exposes `updateData()`, `scrollToIndex()`, `scrollToStart()`, `scrollToEnd()`, and reactive `data` and `refreshing` properties.",
            "Rendered rows are cached by index (capped) and offscreen ones are removed; unmount clears listeners and the cache.",
        ],
        "basic": '''const list = ListView({
  data: ["One", "Two", "Three"],
  renderItem: (item, index) => Text({ text: `${index + 1}. ${item}` }),
});''',
        "normal": '''const list = ListView({
  data: ["One", "Two", "Three"],
  itemSize: 56,
  gap: 8,
  height: 320,
  showsScrollIndicator: true,
  renderItem: (item) => Text({ text: item }),
});''',
        "full": '''const list = ListView({
  data: items,
  itemSize: 64,
  gap: 8,
  expand: true,
  bufferSize: 8,
  onEndReached: () => loadMore(),
  onEndReachedThreshold: 0.4,
  onRefresh: (done) => refreshData(done),
  ListHeaderComponent: () => Text({ text: "Inbox", type: "h3" }),
  ListEmptyComponent: () => Text({ text: "Nothing here yet" }),
  ListFooterComponent: () => Text({ text: "End of list" }),
  renderItem: (item) => ListTile({ title: item.title, subtitle: item.subtitle }),
});''',
    },
    "GridView": {
        "summary": "Grid layout built on ListView's virtualization. It lays items out in a fixed number of columns and gives every cell the same height.",
        "when": "Use GridView for image galleries, product catalogs, and dashboards of equal-sized tiles.",
        "related": ["ListView", "Container", "Card", "Image"],
        "tips": [
            "`columns` sets the number of columns and `spacing` sets the gap between cells.",
            "`itemHeight` fixes each cell's height, which is what makes virtualization possible.",
            "It accepts the same `data` and `renderItem` contract as ListView.",
        ],
        "accessibility": [
            "Announce the grid's purpose with a heading and keep each tile's tap target large enough to hit.",
        ],
        "behavior": [
            "GridView is implemented as ListView with grid wrapping enabled, so it shares the same scrolling and update APIs.",
            "Rows outside the viewport are removed, so keep per-tile state out of the DOM and in widget state when needed.",
        ],
        "basic": '''const grid = GridView({
  data: ["A", "B", "C", "D"],
  renderItem: (item) => Text({ text: item }),
});''',
        "normal": '''const grid = GridView({
  data: products,
  columns: 3,
  spacing: 12,
  itemHeight: 160,
  renderItem: (item) => Card({ child: Text({ text: item.name }) }),
});''',
        "full": '''const grid = GridView({
  data: products,
  columns: 2,
  spacing: 16,
  itemHeight: 180,
  gap: 16,
  height: 480,
  showsScrollIndicator: true,
  onEndReached: () => loadMore(),
  ListEmptyComponent: () => Text({ text: "No products" }),
  renderItem: (item) => Container({
    bgColor: "#ffffff",
    borderRadius: 12,
    child: Text({ text: item.name }),
  }),
});''',
    },
    "Text": {
        "summary": "Renders a string as inline text or as a heading, with control over size, weight, color, alignment, and inline styles.",
        "when": "Use Text for every piece of copy, from body paragraphs and labels to page headings.",
        "related": ["Icon", "Button", "Container", "ListTile"],
        "tips": [
            "Pass content with `text`, `value`, or `children`; `type` maps to the `h1`-`h6` and `p` tags.",
            "`styles` applies inline emphasis such as `bold`, `italic`, `underline`, `strikethrough`, `mark`, or `code`.",
            "`weight` accepts `\"normal\"`, `\"bold\"`, or a numeric value.",
        ],
        "accessibility": [
            "Use heading `type` values in order so the document outline stays meaningful for screen readers.",
        ],
        "behavior": [
            "Heading types `h1`, `h2`, and `p` add a bottom margin; size and color fall back to theme defaults.",
            "Inline `styles` wrap the element in semantic tags such as `strong`, `em`, and `code`.",
        ],
        "basic": '''const title = Text({
  text: "Welcome back",
});''',
        "normal": '''const title = Text({
  text: "Welcome back",
  type: "h2",
  size: 28,
  weight: "bold",
  color: "#111827",
});''',
        "full": '''const body = Text({
  text: "Your subscription renews on Friday.",
  type: "p",
  size: 16,
  weight: "normal",
  color: "#374151",
  align: "left",
  lineHeight: 1.5,
  letterSpacing: 0.2,
  italic: false,
  decoration: "underline",
  styles: ["code"],
  onPress: () => console.log("pressed"),
});''',
    },
    "Button": {
        "summary": "Interactive button with filled, outlined, and text variants, size presets, optional icons, and press feedback.",
        "when": "Use Button for actions such as submit, save, confirm, or any primary and secondary command.",
        "related": ["Icon", "Row", "Column", "FloatingActionButton"],
        "tips": [
            "`variant` defaults to `\"filled\"`; switch to `\"outlined\"` or `\"text\"` for secondary actions.",
            "Place icons with `icon` and `iconPosition`, or use the explicit `iconLeft`, `iconRight`, `iconTop`, `iconBottom` props.",
            "Setting `disabled` also drops the click handler, not just the styling.",
        ],
        "accessibility": [
            "Always pass `text` so the button has an accessible name, and use `disabled` rather than only dimming colors.",
        ],
        "behavior": [
            "Size presets control padding, font size, and icon size; `fullWidth` stretches the button to 100%.",
            "`onPress` receives no arguments and is wired to the native click; `elevation` picks a shadow level.",
        ],
        "basic": '''const save = Button({
  text: "Save",
});''',
        "normal": '''const save = Button({
  text: "Save",
  bgColor: "#2563eb",
  color: "#ffffff",
  borderRadius: 8,
  onPress: () => console.log("saved"),
});''',
        "full": '''const checkout = Button({
  text: "Checkout",
  variant: "filled",
  size: "large",
  gradient: "linear-gradient(90deg, #2563eb, #7c3aed)",
  color: "#ffffff",
  icon: "shopping_cart",
  iconPosition: "right",
  borderRadius: 28,
  elevation: 3,
  fullWidth: true,
  onPress: () => console.log("checkout"),
});''',
    },
    "Icon": {
        "summary": "Material icon glyph rendered as a span. `name` is required and maps to a Material Icons ligature.",
        "when": "Use Icon for compact actions, status indicators, and decoration next to a label.",
        "related": ["Button", "Text", "Row", "ListTile"],
        "tips": [
            "`size` defaults to 24 and `color` falls back to the theme's secondary text color.",
            "Pass a Material Icons name such as `\"settings\"` or `\"chevron_right\"`.",
            "Pair an icon with a visible label when it carries meaning, because the glyph alone is not descriptive.",
        ],
        "accessibility": [
            "Do not rely on the glyph to convey meaning on its own; add an adjacent text label for important actions.",
        ],
        "behavior": [
            "The icon renders as an inline-flex span using the Material Icons class, and it is non-selectable by default.",
            "Supplying `onPress` makes the icon interactive; `size` accepts a number of pixels or a CSS size string.",
        ],
        "basic": '''const settings = Icon({
  name: "settings",
});''',
        "normal": '''const settings = Icon({
  name: "settings",
  size: 28,
  color: "#111827",
});''',
        "full": '''const action = Icon({
  name: "notifications",
  size: 24,
  color: "#2563eb",
  bgColor: "#eff6ff",
  padding: 8,
  borderRadius: 999,
  className: "icon-button",
  onPress: () => console.log("notifications"),
});''',
    },
}
