// core/translateProps.js

/**
 * CENTRAL PROP DATABASE
 *
 * This file defines every prop that the system understands.
 * It is a pure data file – no processing logic here.
 *
 * Each entry:
 *   prop      : custom name used in widgets (e.g., 'w', 'p', 'onClick')
 *   domProp   : corresponding DOM property or CSS property
 *   type      : 'style' | 'attribute' | 'event' | 'text' | 'special'
 *   unit      : (optional) 'rem' | 'px' | 'none' – only for style props
 *   reactive  : (optional) true/false – whether the prop is reactive
 *   expand    : (optional) 'horizontal' | 'vertical' – for shorthands
 */

export const ALL_PROPS = [
  // ==================== FONT FAMILY ====================
  {
    prop: "fontFamily",
    domProp: "fontFamily",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== BACKGROUND (simple) ====================
  {
    prop: "background",
    domProp: "background",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "backgroundAttachment",
    domProp: "backgroundAttachment",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "backgroundOrigin",
    domProp: "backgroundOrigin",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "backgroundClip",
    domProp: "backgroundClip",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "backgroundBlendMode",
    domProp: "backgroundBlendMode",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== FLOAT & CLEAR ====================
  {
    prop: "float",
    domProp: "float",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "clear",
    domProp: "clear",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== VERTICAL ALIGN ====================
  {
    prop: "verticalAlign",
    domProp: "verticalAlign",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== LIST STYLE IMAGE ====================
  {
    prop: "listStyleImage",
    domProp: "listStyleImage",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== COLUMNS ====================
  {
    prop: "columnCount",
    domProp: "columnCount",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "columnWidth",
    domProp: "columnWidth",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "columnGap",
    domProp: "columnGap",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "columnRule",
    domProp: "columnRule",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== TRANSFORM 3D ====================
  {
    prop: "transformStyle",
    domProp: "transformStyle",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "transformBox",
    domProp: "transformBox",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== FLEX ORDER ====================
  {
    prop: "order",
    domProp: "order",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== PRINT & PAGE BREAK ====================
  {
    prop: "orphans",
    domProp: "orphans",
    type: "style",
    unit: "none",
    reactive: false,
  },
  {
    prop: "widows",
    domProp: "widows",
    type: "style",
    unit: "none",
    reactive: false,
  },
  {
    prop: "pageBreakAfter",
    domProp: "pageBreakAfter",
    type: "style",
    unit: "none",
    reactive: false,
  },
  {
    prop: "pageBreakBefore",
    domProp: "pageBreakBefore",
    type: "style",
    unit: "none",
    reactive: false,
  },
  {
    prop: "pageBreakInside",
    domProp: "pageBreakInside",
    type: "style",
    unit: "none",
    reactive: false,
  },

  // ==================== SCROLL SNAP EXTRA ====================
  {
    prop: "scrollSnapAlign",
    domProp: "scrollSnapAlign",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "scrollSnapStop",
    domProp: "scrollSnapStop",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== TOUCH & SCROLL ====================
  {
    prop: "touchAction",
    domProp: "touchAction",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "overscrollBehavior",
    domProp: "overscrollBehavior",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "overscrollBehaviorX",
    domProp: "overscrollBehaviorX",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "overscrollBehaviorY",
    domProp: "overscrollBehaviorY",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== SCROLLBAR STYLING ====================
  {
    prop: "scrollbarWidth",
    domProp: "scrollbarWidth",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "scrollbarColor",
    domProp: "scrollbarColor",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== INPUT & SELECTION COLORS ====================
  {
    prop: "accentColor",
    domProp: "accentColor",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "caretColor",
    domProp: "caretColor",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "colorScheme",
    domProp: "colorScheme",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== CLIP & MASK ====================
  {
    prop: "clipPath",
    domProp: "clipPath",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "mask",
    domProp: "mask",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "maskImage",
    domProp: "maskImage",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "maskSize",
    domProp: "maskSize",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "maskPosition",
    domProp: "maskPosition",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "maskRepeat",
    domProp: "maskRepeat",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== FLEXBOX EXTRA ====================
  {
    prop: "alignContent",
    domProp: "alignContent",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "alignSelf",
    domProp: "alignSelf",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "justifyItems",
    domProp: "justifyItems",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "justifySelf",
    domProp: "justifySelf",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "placeItems",
    domProp: "placeItems",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "placeContent",
    domProp: "placeContent",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "placeSelf",
    domProp: "placeSelf",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== GRID GAP ====================
  {
    prop: "rowGap",
    domProp: "rowGap",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "columnGap",
    domProp: "columnGap",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  // ==================== LOGICAL BOX SIZING ====================
  {
    prop: "blockSize",
    domProp: "blockSize",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "inlineSize",
    domProp: "inlineSize",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "minBlockSize",
    domProp: "minBlockSize",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "maxBlockSize",
    domProp: "maxBlockSize",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "minInlineSize",
    domProp: "minInlineSize",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "maxInlineSize",
    domProp: "maxInlineSize",
    type: "style",
    unit: "rem",
    reactive: true,
  }, // ==================== CONTAINER QUERIES ====================
  {
    prop: "contain",
    domProp: "contain",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "contentVisibility",
    domProp: "contentVisibility",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "container",
    domProp: "container",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "containerType",
    domProp: "containerType",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "containerName",
    domProp: "containerName",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== OFFSET / MOTION PATH ====================
  {
    prop: "offset",
    domProp: "offset",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "offsetPath",
    domProp: "offsetPath",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "offsetDistance",
    domProp: "offsetDistance",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "offsetRotate",
    domProp: "offsetRotate",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== INDIVIDUAL FILTERS ====================
  {
    prop: "brightness",
    domProp: "brightness",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "contrast",
    domProp: "contrast",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "grayscale",
    domProp: "grayscale",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "sepia",
    domProp: "sepia",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "hueRotate",
    domProp: "hueRotate",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "saturate",
    domProp: "saturate",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "invert",
    domProp: "invert",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "blur",
    domProp: "blur",
    type: "style",
    unit: "px",
    reactive: true,
  },

  // ==================== FILTERS ====================
  {
    prop: "filter",
    domProp: "filter",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "backdropFilter",
    domProp: "backdropFilter",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== DIMENSIONS ====================
  { prop: "w", domProp: "width", type: "style", unit: "rem", reactive: true },
  {
    prop: "width",
    domProp: "width",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  { prop: "h", domProp: "height", type: "style", unit: "rem", reactive: true },
  {
    prop: "height",
    domProp: "height",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "minW",
    domProp: "minWidth",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "minWidth",
    domProp: "minWidth",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "maxW",
    domProp: "maxWidth",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "maxWidth",
    domProp: "maxWidth",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "minH",
    domProp: "minHeight",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "minHeight",
    domProp: "minHeight",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "maxH",
    domProp: "maxHeight",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "maxHeight",
    domProp: "maxHeight",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  // ==================== SPACING ====================
  { prop: "p", domProp: "padding", type: "style", unit: "rem", reactive: true },
  {
    prop: "padding",
    domProp: "padding",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  { prop: "m", domProp: "margin", type: "style", unit: "rem", reactive: true },
  {
    prop: "margin",
    domProp: "margin",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "pt",
    domProp: "paddingTop",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "paddingTop",
    domProp: "paddingTop",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "pr",
    domProp: "paddingRight",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "paddingRight",
    domProp: "paddingRight",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "pb",
    domProp: "paddingBottom",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "paddingBottom",
    domProp: "paddingBottom",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "pl",
    domProp: "paddingLeft",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "paddingLeft",
    domProp: "paddingLeft",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "mt",
    domProp: "marginTop",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "marginTop",
    domProp: "marginTop",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "mr",
    domProp: "marginRight",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "marginRight",
    domProp: "marginRight",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "mb",
    domProp: "marginBottom",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "marginBottom",
    domProp: "marginBottom",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "ml",
    domProp: "marginLeft",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "marginLeft",
    domProp: "marginLeft",
    type: "style",
    unit: "rem",
    reactive: true,
  },

  // Shorthands (expand)
  {
    prop: "px",
    domProp: "paddingLeft",
    type: "style",
    unit: "rem",
    reactive: true,
    expand: "horizontal",
  },
  {
    prop: "py",
    domProp: "paddingTop",
    type: "style",
    unit: "rem",
    reactive: true,
    expand: "vertical",
  },
  {
    prop: "mx",
    domProp: "marginLeft",
    type: "style",
    unit: "rem",
    reactive: true,
    expand: "horizontal",
  },
  {
    prop: "my",
    domProp: "marginTop",
    type: "style",
    unit: "rem",
    reactive: true,
    expand: "vertical",
  },
  { prop: "gap", domProp: "gap", type: "style", unit: "rem", reactive: true },

  {
    prop: "ratio",
    domProp: "aspectRatio",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "overflowAuto",
    domProp: "overflow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "overflowHidden",
    domProp: "overflow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "flexCenter",
    domProp: "display",
    type: "style",
    unit: "none",
    reactive: true,
    expand: "flexCenter",
  },
  // ==================== POSITION ====================
  {
    prop: "pos",
    domProp: "position",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "position",
    domProp: "position",
    type: "style",
    unit: "none",
    reactive: true,
  },
  { prop: "z", domProp: "zIndex", type: "style", unit: "none", reactive: true },
  {
    prop: "zIndex",
    domProp: "zIndex",
    type: "style",
    unit: "none",
    reactive: true,
  },
  { prop: "top", domProp: "top", type: "style", unit: "rem", reactive: true },
  {
    prop: "right",
    domProp: "right",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "bottom",
    domProp: "bottom",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  { prop: "left", domProp: "left", type: "style", unit: "rem", reactive: true },
  {
    prop: "inset",
    domProp: "inset",
    type: "style",
    unit: "rem",
    reactive: true,
  },

  // ==================== COLORS ====================
  {
    prop: "bg",
    domProp: "backgroundColor",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "bgColor",
    domProp: "backgroundColor",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "backgroundColor",
    domProp: "backgroundColor",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "textColor",
    domProp: "color",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "color",
    domProp: "color",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "opacity",
    domProp: "opacity",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== TEXT & TYPOGRAPHY ====================
  { prop: "text", domProp: "textContent", type: "text", reactive: true },
  { prop: "label", domProp: "textContent", type: "text", reactive: true },
  { prop: "title", domProp: "textContent", type: "text", reactive: true },
  { prop: "caption", domProp: "textContent", type: "text", reactive: true },
  { prop: "description", domProp: "textContent", type: "text", reactive: true },
  { prop: "message", domProp: "textContent", type: "text", reactive: true },
  { prop: "buttonText", domProp: "textContent", type: "text", reactive: true },

  // ✅ These now correctly go to textContent (no duplicates)
  { prop: "value", domProp: "textContent", type: "text", reactive: true },
  { prop: "name", domProp: "textContent", type: "text", reactive: true },
  { prop: "icon", domProp: "textContent", type: "text", reactive: true },

  {
    prop: "size",
    domProp: "fontSize",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "fontSize",
    domProp: "fontSize",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "weight",
    domProp: "fontWeight",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "fontWeight",
    domProp: "fontWeight",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "textAlign",
    domProp: "textAlign",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "lineH",
    domProp: "lineHeight",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "lineHeight",
    domProp: "lineHeight",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "letterSpace",
    domProp: "letterSpacing",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "letterSpacing",
    domProp: "letterSpacing",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "textDecoration",
    domProp: "textDecoration",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "textTransform",
    domProp: "textTransform",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "whiteSpace",
    domProp: "whiteSpace",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "wordBreak",
    domProp: "wordBreak",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "textOverflow",
    domProp: "textOverflow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "textShadow",
    domProp: "textShadow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "fontStyle",
    domProp: "fontStyle",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "fontVariant",
    domProp: "fontVariant",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "fontStretch",
    domProp: "fontStretch",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "wordSpacing",
    domProp: "wordSpacing",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "wordWrap",
    domProp: "wordWrap",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "hyphens",
    domProp: "hyphens",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "textRendering",
    domProp: "textRendering",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "fontSmoothing",
    domProp: "webkitFontSmoothing",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "textIndent",
    domProp: "textIndent",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  // ==================== APPEARANCE & MISC ====================
  {
    prop: "appearance",
    domProp: "appearance",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "mixBlendMode",
    domProp: "mixBlendMode",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "isolation",
    domProp: "isolation",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== SCROLL ====================
  {
    prop: "scrollBehavior",
    domProp: "scrollBehavior",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "scrollMargin",
    domProp: "scrollMargin",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "scrollPadding",
    domProp: "scrollPadding",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "scrollSnapType",
    domProp: "scrollSnapType",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== OUTLINE ====================
  {
    prop: "outline",
    domProp: "outline",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "outlineWidth",
    domProp: "outlineWidth",
    type: "style",
    unit: "px",
    reactive: true,
  },
  {
    prop: "outlineColor",
    domProp: "outlineColor",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "outlineStyle",
    domProp: "outlineStyle",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "outlineOffset",
    domProp: "outlineOffset",
    type: "style",
    unit: "px",
    reactive: true,
  },
  // ==================== CONTENT (CSS pseudo) ====================
  {
    prop: "content",
    domProp: "content",
    type: "style",
    unit: "none",
    reactive: false,
  },
  {
    prop: "quotes",
    domProp: "quotes",
    type: "style",
    unit: "none",
    reactive: false,
  },
  // ==================== COUNTERS ====================
  {
    prop: "counterIncrement",
    domProp: "counterIncrement",
    type: "style",
    unit: "none",
    reactive: false,
  },
  {
    prop: "counterReset",
    domProp: "counterReset",
    type: "style",
    unit: "none",
    reactive: false,
  },

  // ==================== FLEXBOX ====================
  {
    prop: "direction",
    domProp: "flexDirection",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "flexDirection",
    domProp: "flexDirection",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "justify",
    domProp: "justifyContent",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "justifyContent",
    domProp: "justifyContent",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "align",
    domProp: "alignItems",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "alignItems",
    domProp: "alignItems",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "wrap",
    domProp: "flexWrap",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "flexWrap",
    domProp: "flexWrap",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "flex",
    domProp: "flex",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "flexGrow",
    domProp: "flexGrow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "flexShrink",
    domProp: "flexShrink",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "flexBasis",
    domProp: "flexBasis",
    type: "style",
    unit: "rem",
    reactive: true,
  },

  // ==================== BORDERS & RADIUS ====================
  {
    prop: "rounded",
    domProp: "borderRadius",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "borderRadius",
    domProp: "borderRadius",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "border",
    domProp: "border",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "borderColor",
    domProp: "borderColor",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "borderWidth",
    domProp: "borderWidth",
    type: "style",
    unit: "px",
    reactive: true,
  },
  {
    prop: "borderStyle",
    domProp: "borderStyle",
    type: "style",
    unit: "none",
    reactive: true,
  },

  {
    prop: "roundedTop",
    domProp: "borderTopLeftRadius",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "roundedBottom",
    domProp: "borderBottomLeftRadius",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "roundedLeft",
    domProp: "borderTopLeftRadius",
    type: "style",
    unit: "rem",
    reactive: true,
  },
  {
    prop: "roundedRight",
    domProp: "borderTopRightRadius",
    type: "style",
    unit: "rem",
    reactive: true,
  },

  // ==================== SHADOWS ====================
  {
    prop: "shadow",
    domProp: "boxShadow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "boxShadow",
    domProp: "boxShadow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "elevation",
    domProp: "boxShadow",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== DISPLAY & LAYOUT ====================
  {
    prop: "display",
    domProp: "display",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "expand",
    domProp: "flex",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "overflow",
    domProp: "overflow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "overflowX",
    domProp: "overflowX",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "overflowY",
    domProp: "overflowY",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "cursor",
    domProp: "cursor",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "visibility",
    domProp: "visibility",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "pointerEvents",
    domProp: "pointerEvents",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "userSelect",
    domProp: "userSelect",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "boxSizing",
    domProp: "boxSizing",
    type: "style",
    unit: "none",
    reactive: true,
  },

  {
    prop: "resize",
    domProp: "resize",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== GRID ====================
  {
    prop: "gridTemplateColumns",
    domProp: "gridTemplateColumns",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridTemplateRows",
    domProp: "gridTemplateRows",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridTemplateAreas",
    domProp: "gridTemplateAreas",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridAutoColumns",
    domProp: "gridAutoColumns",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridAutoRows",
    domProp: "gridAutoRows",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridAutoFlow",
    domProp: "gridAutoFlow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridColumn",
    domProp: "gridColumn",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridRow",
    domProp: "gridRow",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridColumnStart",
    domProp: "gridColumnStart",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridColumnEnd",
    domProp: "gridColumnEnd",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridRowStart",
    domProp: "gridRowStart",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "gridRowEnd",
    domProp: "gridRowEnd",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== BACKGROUND ====================
  {
    prop: "gradient",
    domProp: "background",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "bgImage",
    domProp: "backgroundImage",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "bgSize",
    domProp: "backgroundSize",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "bgPosition",
    domProp: "backgroundPosition",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "bgRepeat",
    domProp: "backgroundRepeat",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== TABLE ====================
  {
    prop: "tableLayout",
    domProp: "tableLayout",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "borderCollapse",
    domProp: "borderCollapse",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "borderSpacing",
    domProp: "borderSpacing",
    type: "style",
    unit: "px",
    reactive: true,
  },
  {
    prop: "captionSide",
    domProp: "captionSide",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "emptyCells",
    domProp: "emptyCells",
    type: "style",
    unit: "none",
    reactive: true,
  },

  // ==================== LIST STYLES ====================

  {
    prop: "listStyle",
    domProp: "listStyle",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "listStyleType",
    domProp: "listStyleType",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "listStylePosition",
    domProp: "listStylePosition",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== IMAGES / OBJECT ====================
  {
    prop: "objectFit",
    domProp: "objectFit",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "objectPosition",
    domProp: "objectPosition",
    type: "style",
    unit: "none",
    reactive: true,
  },
  // ==================== ANIMATIONS & TRANSITIONS ====================
  {
    prop: "transition",
    domProp: "transition",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "animation",
    domProp: "animation",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "transform",
    domProp: "transform",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "willChange",
    domProp: "willChange",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "backfaceVisibility",
    domProp: "backfaceVisibility",
    type: "style",
    unit: "none",
    reactive: true,
  },
  {
    prop: "perspective",
    domProp: "perspective",
    type: "style",
    unit: "px",
    reactive: true,
  },
  // ==================== ARIA ATTRIBUTES ====================
  { prop: "ariaLabel", domProp: "aria-label", type: "attribute" },
  { prop: "ariaHidden", domProp: "aria-hidden", type: "attribute" },
  { prop: "ariaExpanded", domProp: "aria-expanded", type: "attribute" },
  { prop: "ariaControls", domProp: "aria-controls", type: "attribute" },
  { prop: "ariaDescribedby", domProp: "aria-describedby", type: "attribute" },
  { prop: "ariaLabelledby", domProp: "aria-labelledby", type: "attribute" },
  // ==================== HTML ATTRIBUTES ====================
  // NOTE: 'value' and 'name' have been removed from here – they are now 'text' props.
  { prop: "id", domProp: "id", type: "attribute" },
  { prop: "className", domProp: "className", type: "attribute" },
  { prop: "class", domProp: "className", type: "attribute" },
  // name is now in TEXT section – remove duplicate
  { prop: "type", domProp: "type", type: "attribute" },
  { prop: "href", domProp: "href", type: "attribute" },
  { prop: "src", domProp: "src", type: "attribute" },
  { prop: "alt", domProp: "alt", type: "attribute" },
  { prop: "disabled", domProp: "disabled", type: "attribute" },
  { prop: "readOnly", domProp: "readOnly", type: "attribute" },
  { prop: "required", domProp: "required", type: "attribute" },
  { prop: "checked", domProp: "checked", type: "attribute" },
  { prop: "selected", domProp: "selected", type: "attribute" },
  { prop: "placeholder", domProp: "placeholder", type: "attribute" },
  // value is now in TEXT section – remove duplicate
  { prop: "min", domProp: "min", type: "attribute" },
  { prop: "max", domProp: "max", type: "attribute" },
  { prop: "step", domProp: "step", type: "attribute" },
  { prop: "pattern", domProp: "pattern", type: "attribute" },
  { prop: "role", domProp: "role", type: "attribute" },
  { prop: "title", domProp: "title", type: "attribute" }, // note: there's a text 'title' too – this one is the HTML attribute
  { prop: "lang", domProp: "lang", type: "attribute" },
  { prop: "dir", domProp: "dir", type: "attribute" },
  { prop: "tabIndex", domProp: "tabIndex", type: "attribute" },
  { prop: "draggable", domProp: "draggable", type: "attribute" },
  { prop: "hidden", domProp: "hidden", type: "attribute" },
  { prop: "for", domProp: "htmlFor", type: "attribute" },
  { prop: "htmlFor", domProp: "htmlFor", type: "attribute" },
  { prop: "autofocus", domProp: "autofocus", type: "attribute" },
  { prop: "autocomplete", domProp: "autocomplete", type: "attribute" },
  { prop: "spellcheck", domProp: "spellcheck", type: "attribute" },

  // ==================== EVENTS ====================
  { prop: "onPress", domProp: "click", type: "event" },
  { prop: "onClick", domProp: "click", type: "event" },
  { prop: "onDoublePress", domProp: "dblclick", type: "event" },
  { prop: "onRightClick", domProp: "contextmenu", type: "event" },
  { prop: "onHover", domProp: "mouseenter", type: "event" },
  { prop: "onHoverEnd", domProp: "mouseleave", type: "event" },
  { prop: "onFocus", domProp: "focus", type: "event" },
  { prop: "onBlur", domProp: "blur", type: "event" },
  { prop: "onChange", domProp: "change", type: "event" },
  { prop: "onInput", domProp: "input", type: "event" },
  { prop: "onScroll", domProp: "scroll", type: "event" },
  { prop: "onKeyDown", domProp: "keydown", type: "event" },
  { prop: "onKeyUp", domProp: "keyup", type: "event" },
  { prop: "onKeyPress", domProp: "keypress", type: "event" },
  { prop: "onMouseDown", domProp: "mousedown", type: "event" },
  { prop: "onMouseUp", domProp: "mouseup", type: "event" },
  { prop: "onMouseMove", domProp: "mousemove", type: "event" },
  { prop: "onTouchStart", domProp: "touchstart", type: "event" },
  { prop: "onTouchMove", domProp: "touchmove", type: "event" },
  { prop: "onTouchEnd", domProp: "touchend", type: "event" },

  // ==================== SPECIAL (handled elsewhere) ====================
  { prop: "ref", domProp: "ref", type: "special" },
  { prop: "child", domProp: "child", type: "special" },
  { prop: "children", domProp: "children", type: "special" },
  { prop: "style", domProp: "style", type: "special" },
  // ==================== HTML ATTRIBUTES ====================
  { prop: "target", domProp: "target", type: "attribute" },
  { prop: "rel", domProp: "rel", type: "attribute" },
  { prop: "download", domProp: "download", type: "attribute" },
  { prop: "media", domProp: "media", type: "attribute" },
  { prop: "crossOrigin", domProp: "crossOrigin", type: "attribute" },
  { prop: "referrerPolicy", domProp: "referrerPolicy", type: "attribute" },
  { prop: "async", domProp: "async", type: "attribute" },
  { prop: "defer", domProp: "defer", type: "attribute" },
  { prop: "integrity", domProp: "integrity", type: "attribute" },
  { prop: "loading", domProp: "loading", type: "attribute" }, // 'lazy', 'eager'
  { prop: "decoding", domProp: "decoding", type: "attribute" }, // 'sync', 'async', 'auto'
  { prop: "fetchPriority", domProp: "fetchPriority", type: "attribute" }, // 'high', 'low', 'auto'
  { prop: "inputMode", domProp: "inputMode", type: "attribute" }, // 'text', 'numeric', etc.
  { prop: "autoCapitalize", domProp: "autoCapitalize", type: "attribute" },
  { prop: "autoComplete", domProp: "autoComplete", type: "attribute" },
  { prop: "autoFocus", domProp: "autoFocus", type: "attribute" }, // ✅ ya tienes autofocus
  { prop: "autoPlay", domProp: "autoPlay", type: "attribute" },
  { prop: "controls", domProp: "controls", type: "attribute" },
  { prop: "loop", domProp: "loop", type: "attribute" },
  { prop: "muted", domProp: "muted", type: "attribute" },
  { prop: "poster", domProp: "poster", type: "attribute" },
  { prop: "preload", domProp: "preload", type: "attribute" },
  { prop: "playsInline", domProp: "playsInline", type: "attribute" },
  { prop: "form", domProp: "form", type: "attribute" },
  { prop: "formAction", domProp: "formAction", type: "attribute" },
  { prop: "formMethod", domProp: "formMethod", type: "attribute" },
  { prop: "formNoValidate", domProp: "formNoValidate", type: "attribute" },
  { prop: "formTarget", domProp: "formTarget", type: "attribute" },
  { prop: "accept", domProp: "accept", type: "attribute" },
  { prop: "acceptCharset", domProp: "acceptCharset", type: "attribute" },
  { prop: "encType", domProp: "encType", type: "attribute" },
  { prop: "method", domProp: "method", type: "attribute" },
  { prop: "action", domProp: "action", type: "attribute" },
  { prop: "novalidate", domProp: "noValidate", type: "attribute" },
  { prop: "multiple", domProp: "multiple", type: "attribute" },
  { prop: "size", domProp: "size", type: "attribute" }, // ⚠️ cuidado: ya hay 'size' como fontSize (style)
  { prop: "maxLength", domProp: "maxLength", type: "attribute" },
  { prop: "minLength", domProp: "minLength", type: "attribute" },
  { prop: "colspan", domProp: "colSpan", type: "attribute" },
  { prop: "rowspan", domProp: "rowSpan", type: "attribute" },
  { prop: "scope", domProp: "scope", type: "attribute" },
  { prop: "headers", domProp: "headers", type: "attribute" },
  // ==================== ADDITIONAL HTML ATTRIBUTES ====================
  { prop: "sandbox", domProp: "sandbox", type: "attribute" },
  { prop: "allow", domProp: "allow", type: "attribute" },
  { prop: "allowFullscreen", domProp: "allowFullscreen", type: "attribute" },
  {
    prop: "allowPaymentRequest",
    domProp: "allowPaymentRequest",
    type: "attribute",
  },
  {
    prop: "allowTransparency",
    domProp: "allowTransparency",
    type: "attribute",
  },
  { prop: "challenge", domProp: "challenge", type: "attribute" },
  { prop: "keytype", domProp: "keytype", type: "attribute" },
  { prop: "keyparams", domProp: "keyparams", type: "attribute" },
  { prop: "manifest", domProp: "manifest", type: "attribute" },
  { prop: "seamless", domProp: "seamless", type: "attribute" },
  { prop: "srcdoc", domProp: "srcdoc", type: "attribute" },
  { prop: "srclang", domProp: "srclang", type: "attribute" },
  { prop: "srcset", domProp: "srcset", type: "attribute" },
  { prop: "sizes", domProp: "sizes", type: "attribute" },
  { prop: "crossorigin", domProp: "crossorigin", type: "attribute" },
];

// ============================================================
// DERIVED MAPS
// ============================================================

export const PROP_MAP = Object.fromEntries(ALL_PROPS.map((p) => [p.prop, p]));
export const DOM_PROP_MAP = Object.fromEntries(
  ALL_PROPS.map((p) => [p.domProp, p]),
);

export const STYLE_PROPS = ALL_PROPS.filter((p) => p.type === "style").map(
  (p) => p.prop,
);
export const ATTRIBUTE_PROPS = ALL_PROPS.filter(
  (p) => p.type === "attribute",
).map((p) => p.prop);
export const EVENT_PROPS = ALL_PROPS.filter((p) => p.type === "event").map(
  (p) => p.prop,
);
export const TEXT_PROPS = ALL_PROPS.filter((p) => p.type === "text").map(
  (p) => p.prop,
);
export const REACTIVE_PROPS = ALL_PROPS.filter((p) => p.reactive).map(
  (p) => p.prop,
);

export const UNIT_MAP = Object.fromEntries(
  ALL_PROPS.filter((p) => p.type === "style" && p.unit).map((p) => [
    p.domProp,
    p.unit,
  ]),
);

export const ATTRIBUTE_DOM_SET = new Set(
  ALL_PROPS.filter((p) => p.type === "attribute").map((p) => p.domProp),
);
export const EVENT_DOM_SET = new Set(
  ALL_PROPS.filter((p) => p.type === "event").map((p) => p.domProp),
);
export const TEXT_PROP_SET = new Set(TEXT_PROPS);

// ============================================================
// LOOKUP FUNCTION WITH WARNING
// ============================================================

export function getPropDefinition(propName) {
  const def = PROP_MAP[propName];
  if (!def) {
    console.warn(
      `⚠️ [FletBox] Unknown prop: "${propName}". ` +
        `Check your spelling or add it to the prop database.`,
    );
    return null;
  }
  return def;
}

export default {
  ALL_PROPS,
  PROP_MAP,
  DOM_PROP_MAP,
  STYLE_PROPS,
  ATTRIBUTE_PROPS,
  EVENT_PROPS,
  TEXT_PROPS,
  REACTIVE_PROPS,
  UNIT_MAP,
  ATTRIBUTE_DOM_SET,
  EVENT_DOM_SET,
  TEXT_PROP_SET,
  getPropDefinition,
};
