"""Curated data for the FletBox widget documentation generator.

`WIDGET_DOCS`     per-widget prose + examples (authored in `_docdata/group*.py`)
`BOOK`            the ordered reading path (chapters + widget order)
`DESC`            real property descriptions used by the prop tables
`ALIASES`         the canonical prop aliases resolved by the widget factory
"""

from _docdata.group1 import WIDGET_DOCS as _g1
from _docdata.group2 import WIDGET_DOCS as _g2
from _docdata.group3 import WIDGET_DOCS as _g3
from _docdata.group4 import WIDGET_DOCS as _g4
from _docdata.group5 import WIDGET_DOCS as _g5

WIDGET_DOCS = {**_g1, **_g2, **_g3, **_g4, **_g5}

# The widget pages that are part of the generated book. Chapter 8 pages
# (Scaffold, AppBar, Drawer, ...) are hand-written and live alongside these.
BOOK = [
    (
        "Chapter 1 · First steps: the core mental model",
        ["Text", "Container", "Row", "Column", "Stack", "Icon", "Image"],
    ),
    (
        "Chapter 2 · Interaction basics",
        ["Button", "Input", "Checkbox", "Radio", "Switch", "Slider", "Dropdown", "Rating"],
    ),
    (
        "Chapter 3 · Layout, cards and lists",
        ["Card", "Divider", "ListTile", "ListView", "GridView", "Avatar", "Badge", "Chip"],
    ),
    (
        "Chapter 4 · Feedback and overlays",
        [
            "AlertDialog", "Modal", "BottomSheet", "SnackBar", "Tooltip",
            "ProgressBar", "CircularBar", "Skeleton", "FloatingActionButton", "Pagination",
        ],
    ),
    (
        "Chapter 5 · Navigation and flows",
        ["Stepper", "Accordion", "TreeView", "Carousel", "InstallButton"],
    ),
    (
        "Chapter 6 · Data, rich content & effects",
        [
            "DataTable", "Chart", "CircularChart", "Markdown", "CodeViewer", "QRCode",
            "Inspector", "AdSense", "AdMob",
            "AnimatedBox", "AnimatedText", "MatrixRain", "ParallaxBox",
        ],
    ),
    (
        "Chapter 7 · Media and drag & drop",
        ["Audio", "Video", "DraggBox", "DroppBox"],
    ),
]

# Chapter 8 is hand-written. Its opener follows the last Chapter 7 page.
NEXT_AFTER_BOOK = "Scaffold"

ALIASES = {
    "backgroundColor": "bgColor",
    "onClick": "onPress",
    "child": "children",
}

DESC = {
    # CommonProps
    "width": "Width of the widget. A number is pixels; a string uses any CSS unit.",
    "height": "Height of the widget. A number is pixels; a string uses any CSS unit.",
    "size": "Overall size preset or pixel value, depending on the widget.",
    "padding": "Space inside the widget, between its content and its border.",
    "margin": "Space outside the widget, between it and its neighbors.",
    "bgColor": "Background color. Alias: `backgroundColor`.",
    "color": "Foreground color, usually the text or icon color.",
    "borderRadius": "Rounds the corners of the widget.",
    "elevation": "Shadow depth. Higher values lift the widget off the page.",
    "shadow": "Raw CSS `box-shadow` value, for a custom shadow.",
    "opacity": "Opacity from 0 (invisible) to 1 (fully opaque).",
    "visible": "Whether the widget is rendered and visible.",
    "disabled": "Disables interaction and shows the non-interactive state.",
    "onPress": "Callback fired when the widget is pressed. Alias: `onClick`.",
    "onClick": "Callback fired when the widget is clicked. Alias: `onPress`.",
    "id": "DOM `id` for the rendered element.",
    "className": "CSS class names applied to the rendered element.",
    "ref": "Callback that receives the underlying DOM node.",
    "disableTransform": "Disables the default press/scale transform animation.",
    "child": "A single child widget. Alias: `children` for a list.",
    "children": "An array of child widgets. Alias: `child` for a single child.",
    # Layout
    "direction": "Main-axis direction for layout widgets (`row` or `column`).",
    "gap": "Space between children along the layout axis.",
    "justifyContent": "Aligns children along the main axis (CSS `justify-content`).",
    "alignItems": "Aligns children across the cross axis (CSS `align-items`).",
    "wrap": "Lets children wrap onto multiple lines.",
    "expand": "Lets a flex child grow to fill available space.",
    "flex": "Flex grow/shrink/basis shorthand for a flex child.",
    "overflow": "How overflowing content is handled (`hidden`, `auto`, `scroll`).",
    "minWidth": "Minimum width the widget may shrink to.",
    "maxWidth": "Maximum width the widget may grow to.",
    "minHeight": "Minimum height the widget may shrink to.",
    "maxHeight": "Maximum height the widget may grow to.",
    "position": "CSS `position` value, or `stack` for centered stacking.",
    "alignment": "How children are aligned inside the stack.",
    "display": "CSS `display` value for the container.",
    "spacing": "Space between grid items.",
    "columns": "Number of grid columns.",
    "itemHeight": "Height of each grid cell.",
    # ListView / GridView
    "data": "Array of items rendered by the list.",
    "renderItem": "Builds one child from an item: `(item, index) => Widget`.",
    "itemSize": "Height of each list item.",
    "wrapItems": "Enables grid wrapping of list items.",
    "crossAxisCount": "Number of items per row when wrapping.",
    "onEndReached": "Fired when the list scrolls near its end, for infinite loading.",
    "onEndReachedThreshold": "How close to the end (in items or px) triggers `onEndReached`.",
    "onRefresh": "Pull-to-refresh handler; call the provided `done()` when finished.",
    "ListHeaderComponent": "Widget or builder rendered above the list content.",
    "ListFooterComponent": "Widget or builder rendered below the list content.",
    "ListEmptyComponent": "Widget or builder shown when there is no data.",
    "showsScrollIndicator": "Shows the native scrollbar.",
    "bufferSize": "How many extra items to render beyond the viewport.",
    # Text
    "text": "Visible text content.",
    "value": "Current value controlled by the widget.",
    "weight": "Font weight, such as `normal`, `bold`, or a number.",
    "align": "Horizontal text alignment.",
    "italic": "Renders the text in italics.",
    "decoration": "Text decoration such as `underline` or `line-through`.",
    "lineHeight": "Line height as a number multiplier or CSS value.",
    "letterSpacing": "Extra space between letters.",
    "type": "Semantic type or heading level, such as `h1` or `body`.",
    "styles": "Extra inline styles applied to the text.",
    # Button / actions
    "variant": "Visual variation or style preset.",
    "gradient": "CSS gradient used as the fill.",
    "textColor": "Color of the button label.",
    "fullWidth": "Stretches the widget to the full width of its parent.",
    "icon": "Name of the icon to render.",
    "iconLeft": "Icon shown to the left of the label.",
    "iconRight": "Icon shown to the right of the label.",
    "iconTop": "Icon shown above the label.",
    "iconBottom": "Icon shown below the label.",
    "iconPosition": "Where the icon sits relative to the label.",
    "label": "Label or caption shown near the control.",
    "extended": "Extends the FAB to show a label next to the icon.",
    "mini": "Renders the small variant of the floating action button.",
    "backgroundColor": "Background color. Alias of `bgColor`.",
    "foregroundColor": "Color of the icon and label.",
    # Media
    "src": "Resource URL for the image, audio, or video.",
    "alt": "Alternative text for an image, for accessibility.",
    "fit": "How the image fits its box (CSS `object-fit`).",
    "circular": "Clips the image into a circle.",
    "onLoad": "Fired when the media finishes loading.",
    "onError": "Fired when the media fails to load.",
    "controls": "Shows the native media playback controls.",
    "autoplay": "Starts playback automatically.",
    "loop": "Restarts playback when it reaches the end.",
    "muted": "Starts playback with the audio muted.",
    "poster": "Image shown before a video starts playing.",
    "volume": "Initial volume from 0 to 1.",
    "onPlay": "Fired when playback starts.",
    "onPause": "Fired when playback is paused.",
    "onEnd": "Fired when playback reaches the end.",
    "onTimeUpdate": "Fired repeatedly as the playback position changes.",
    "onProgress": "Fired as the media buffers.",
    # Forms / inputs
    "placeholder": "Hint text shown when the field is empty.",
    "error": "Error flag or message shown under the field.",
    "readonly": "Makes the field read-only while keeping it focusable.",
    "readOnly": "Makes the control read-only.",
    "required": "Marks the field as required and validates it.",
    "validation": "Built-in validation rule, such as `email` or `numbers`.",
    "maxLength": "Maximum number of characters accepted.",
    "iconColor": "Color of the field icons.",
    "iconSize": "Size of the field icons.",
    "onIconPress": "Fired when a field icon is pressed.",
    "clearable": "Shows a button that clears the field.",
    "passwordToggle": "Shows a button that reveals or hides a password.",
    "showValidationMessage": "Shows the validation message under the field.",
    "showValidationIcon": "Shows a valid/invalid icon inside the field.",
    "customPattern": "Regular expression used by `validation: \"custom\"`.",
    "onValidated": "Fired with `(isValid, message)` after validation.",
    "onChange": "Fired when the value changes.",
    "onInput": "Fired on every keystroke while typing.",
    "onFocus": "Fired when the control gains focus.",
    "onBlur": "Fired when the control loses focus.",
    "onEnter": "Fired when Enter is pressed in the field.",
    "checked": "Current checked state.",
    "onCheck": "Fired with the new checked state.",
    "selected": "Current selected state.",
    "onSelect": "Fired when the widget or an option is selected.",
    "onToggle": "Fired with the new toggled state.",
    "activeColor": "Color used in the active state.",
    "inactiveColor": "Color used in the inactive state.",
    "trackColor": "Color of the slider track.",
    "thumbSize": "Size of the slider thumb.",
    "step": "Increment between allowed slider values.",
    "min": "Minimum allowed value.",
    "max": "Maximum allowed value.",
    "orientation": "Orientation of the widget or control.",
    "inverted": "Reverses the direction of the control.",
    "options": "Available options for a selection widget.",
    "optionHoverColor": "Background color of an option while hovered.",
    "portal": "Renders the dropdown menu in a portal above the page.",
    "allowHalf": "Allows half-star ratings.",
    "allowDangerousHtml": "Allows raw HTML inside markdown output.",
    # Feedback / overlays
    "open": "Controls whether the overlay is visible.",
    "title": "Title text shown in the header.",
    "message": "Body text or notification content.",
    "content": "Main content of the overlay.",
    "actions": "Widgets rendered in the overlay footer.",
    "closeOnOverlayClick": "Closes the overlay when the backdrop is clicked.",
    "closeOnEsc": "Closes the overlay when Escape is pressed.",
    "closeOnDragDown": "Closes the sheet when dragged down.",
    "showCloseButton": "Shows a close button in the header.",
    "showDragHandle": "Shows the drag handle above the sheet.",
    "overlayColor": "Color of the dimmed backdrop behind the overlay.",
    "onOpen": "Fired when the overlay opens.",
    "onClose": "Fired when the overlay closes.",
    "onConfirm": "Fired when the confirm action is pressed.",
    "onCancel": "Fired when the cancel action is pressed.",
    "confirmText": "Label of the confirm button.",
    "cancelText": "Label of the cancel button.",
    "showCancel": "Shows the cancel button.",
    "duration": "How long the transient element stays visible, in milliseconds.",
    "indeterminate": "Shows an unknown-progress animation.",
    "striped": "Draws diagonal stripes across the bar.",
    "animatedStripes": "Animates the stripes on the bar.",
    "showValue": "Shows the numeric value next to the indicator.",
    "valuePosition": "Where the value label is placed.",
    # Data / rich content
    "rows": "Data rows rendered by the table.",
    "hoverable": "Highlights rows on hover.",
    "bordered": "Draws borders around cells.",
    "onRowClick": "Fired with the clicked row.",
    "stripedRowBgColor": "Background color for alternating rows.",
    "headerBgColor": "Background color of the header row.",
    "headerTextColor": "Text color of the header row.",
    "cellPadding": "Padding inside each cell.",
    "labels": "Axis or slice labels for the chart.",
    "candleWidth": "Width of each candlestick.",
    "showGrid": "Shows the chart grid lines.",
    "showLabels": "Shows chart labels.",
    "smooth": "Draws a smoothed line instead of straight segments.",
    "areaGradient": "Fills the area under the line with a gradient.",
    "code": "Source code to display.",
    "language": "Language used to highlight the code.",
    "showLineNumbers": "Shows line numbers in the gutter.",
    "showHeader": "Shows the code viewer header.",
    "widget": "The DOM node or widget to inspect.",
    "indent": "Indentation depth used when printing nested structures.",
    # Charts (circular)
    "data": "Array of values or `{ label, value }` slices.",
    "strokeWidth": "Thickness of the circular stroke.",
    "innerRadius": "Radius of the empty center of a donut.",
    "startAngle": "Starting angle of the arc, in degrees.",
    "endAngle": "Ending angle of the arc, in degrees.",
    "centerContent": "Widget rendered in the center of the circle.",
    "dot": "Shows a small dot instead of a count.",
    "max": "Maximum value used to compute the ratio.",
    # Navigation / flows
    "steps": "Step definitions rendered by the stepper.",
    "activeStep": "Index of the currently active step.",
    "onStepChange": "Fired with the new active step index.",
    "nodes": "Tree nodes, each with `id`, `label`, and optional `children`.",
    "expandedNodes": "Ids of nodes that start expanded.",
    "defaultExpanded": "Expands top-level nodes by default.",
    "selectable": "Lets the user select a tree node.",
    "selectedNodeId": "Id of the currently selected node.",
    "items": "Array of items rendered in a rotating or grouped widget.",
    "autoPlay": "Advances automatically.",
    "interval": "Delay between automatic advances, in milliseconds.",
    "showArrows": "Shows previous/next arrows.",
    "showDots": "Shows the dot indicators.",
    "infinite": "Loops from the last item back to the first.",
    "onIndexChange": "Fired with the new active index.",
    "totalItems": "Total number of items to paginate.",
    "pageSize": "Number of items per page.",
    "currentPage": "Currently active page.",
    "onPageChange": "Fired with the new page number.",
    "showFirstLast": "Shows first and last page buttons.",
    "showPrevNext": "Shows previous and next page buttons.",
    "maxButtons": "Maximum number of page buttons before truncation.",
    "onInstalled": "Fired when the PWA finishes installing.",
    # Drag and drop
    "group": "Drag group name; only matching targets accept the item.",
    "onDragStart": "Fired when dragging starts.",
    "onDragEnd": "Fired when dragging ends.",
    "onDrop": "Fired when an item is dropped on the target.",
    "onDragEnter": "Fired when a dragged item enters the target.",
    "onDragLeave": "Fired when a dragged item leaves the target.",
    "onDragOver": "Fired continuously while an item is dragged over the target.",
    "acceptGroups": "Drag groups this target accepts.",
    "cloneOnDrag": "Keeps the original element while dragging a clone.",
    "dragImage": "Custom image shown while dragging.",
    "showFeedback": "Shows valid/invalid feedback during a drag.",
    # Animation
    "animations": "Animations to apply, as a name or an array of names.",
    "timing": "Timing function for the animation.",
    "delay": "Delay before the animation starts, in milliseconds.",
    "fillMode": "How styles persist before and after the animation (CSS `fill-mode`).",
    "sameTime": "Runs child animations at the same time.",
    "delayBetween": "Stagger delay between each child animation.",
    "chars": "Characters used by the matrix rain.",
    "speed": "Animation speed.",
    "fadeAmount": "How quickly trails fade each frame.",
    "resetProbability": "Chance a column resets to the top each frame.",
    "useDynamicColor": "Cycles colors instead of using a fixed color.",
    "type": "Kind or mode of the widget.",
    "maxOffset": "Maximum parallax offset in pixels.",
    "reverse": "Reverses the parallax direction.",
    "easing": "Easing curve for the parallax motion.",
    "onParallaxMove": "Fired as the parallax offset changes.",
    # Progress / circular bar
    "valueFormat": "Formats the displayed value.",
    "valueSuffix": "Text appended after the displayed value.",
    "valuePrefix": "Text prepended before the displayed value.",
    "valueDecimals": "Number of decimals in the displayed value.",
    "customValueFormatter": "Function that returns the formatted value string.",
    "glow": "Adds a glow around the widget.",
    "glowColor": "Color of the glow.",
    "markers": "Marker ticks drawn along the progress arc.",
    "lineCap": "Shape of the ends of the progress stroke.",
    # Markdown
    "source": "Markdown source string to render.",
    "linkColor": "Color of links in rendered markdown.",
    "codeBgColor": "Background color of inline code.",
    "preBgColor": "Background color of code blocks.",
    "headingColor": "Color of markdown headings.",
    # Ads
    "client": "AdSense publisher id, such as `ca-pub-...`.",
    "slot": "AdSense ad unit slot id.",
    "format": "Ad format requested from the ad network.",
    "responsive": "Lets the ad resize to fit its container.",
    "placeholder": "Fallback text shown while the ad is unavailable.",
    "adId": "AdMob ad unit id.",
    "isTesting": "Requests test ads instead of live ones.",
    "interstitialId": "AdMob interstitial ad unit id.",
    "rewardedId": "AdMob rewarded ad unit id.",
    "autoShow": "Shows the ad automatically when it is ready.",
    "onLoaded": "Fired when the ad loads.",
    "onFailed": "Fired when the ad fails to load.",
    "onDismissed": "Fired when the ad is dismissed.",
}

# Pattern fallbacks were removed; use DESC and the automatic humanizer instead.
# (kept as an empty list to avoid import errors in other files)
DESCRIPTION_FALLBACKS = []
